name: build

on: [push, pull_request]

jobs:
  tests:
    name: Node ${{ matrix.node_version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [10, 12]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}

      - name: Setup submodule
        run: |
          git submodule init
          git submodule update

      - name: unit-tests
        run: |
          npm install
          npm test

  functional-tests:
    needs: tests
    name: FTs ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Set up Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Clone gauge
        run: |
          git clone https://github.com/getgauge/gauge

      - name: Build gauge
        run: |
          cd gauge
          go run -mod=vendor build/make.go --verbose

      - name: Install Gauge (windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd gauge
          go run -mod=vendor build/make.go --install  --verbose
          echo "::add-path::C:\\Program Files\\gauge\\bin"

      - name: Install Gauge (linux)
        if: matrix.os != 'windows-latest'
        run: |
          cd gauge
          go run -mod=vendor build/make.go --install --prefix=/tmp/gauge --verbose
          echo "::add-path::/tmp/gauge/bin"

      - name: Install JS
        run: |
          npm install
          npm run installPlugin

      - name: Prep FTs
        run: |
          git clone https://github.com/getgauge/gauge-tests
          cd gauge-tests
          gauge install

      - name: Run FTs (linux)
        if: matrix.os != 'windows-latest'
        run: |
          cd gauge-tests
          ./gradlew clean jsFT

      - name: Run FTs (windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd gauge-tests
          .\gradlew.bat clean jsFT
